# Use an official Node.js runtime as the base image
FROM node:21-alpine
# test webwook
# Set environment variables for the application using .env file
# [REACT_APP_EMAILJS_SERVICE_ID, REACT_APP_EMAILJS_TEMPLATE_ID, REACT_APP_EMAILJS_USER_ID]

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json (or yarn.lock) files to the container
COPY package*.json ./

# Install the application's dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY public/ ./public
COPY src/ ./src

# Expose port 3000 to the host machine
EXPOSE 3000

# Command to start the development server
CMD ["npm", "run", "start"]
