version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
    - ./src:/app/src
    - ./public:/app/public
